name: Send Random English Messages

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send random message to group
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN2 }}
        run: |
          MESSAGES=(
            "Hello 👋 How's everyone doing today?"
            "Hi there! What are you up to right now?"
            "Is anyone here? Let's chat! "
            "Good morning"
            "Good evening How was your day?"
            "Hey nice to meet you"
            "Hello friends dm me"
            "Hi! What's on your mind right now?"
            "What are you passionate about?"
            "Hey guys"
            "Hello"
            "Hi anyone here"
            " What's one thing you're grateful for today?"
            "Hey 👋"
            "Hello! how is it going"
            "Hi everyone! Any weekend plans? "
            "Hi how are you?"
            "Hey! What's up"
            "Hello! Coffee or tea? "
            "Hi do you love me "
          )
          
          RANDOM_INDEX=$((RANDOM % ${#MESSAGES[@]}))
          RANDOM_MESSAGE="${MESSAGES[$RANDOM_INDEX]}"
          
          echo "Selected message: $RANDOM_MESSAGE"
          
          curl -s -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendMessage \
          -d chat_id=-1002507938213 \
          -d text="$RANDOM_MESSAGE"
          
          echo "Message sent successfully!"
